#include <iostream>

#include "symaware/prescan/entity.h"
#include "symaware/prescan/environment.h"
#include "symaware/prescan/road.h"
#include "symaware/util/exception.h"
#include "symaware_prescan.h"

namespace py = pybind11;

void init_environment(py::module_ &m) {
  py::class_<symaware::Environment> environment = py::class_<symaware::Environment>(m, "_Environment");

  py::enum_<symaware::Environment::WeatherType>(environment, "WeatherType")
      .value("SUNNY", symaware::Environment::WeatherType::SUNNY)
      .value("RAINY", symaware::Environment::WeatherType::RAINY)
      .value("SNOWY", symaware::Environment::WeatherType::SNOWY);

  py::enum_<symaware::Environment::SkyType>(environment, "SkyType")
      .value("DAY", symaware::Environment::SkyType::DAY)
      .value("NIGHT", symaware::Environment::SkyType::NIGHT)
      .value("DAWN", symaware::Environment::SkyType::DAWN)
      .value("DUSK", symaware::Environment::SkyType::DUSK);

  py::enum_<symaware::Environment::ObjectType>(environment, "ObjectType")
      .value("ADAC_target_yellow_merc", symaware::Environment::ObjectType::ADAC_target_yellow_merc)
      .value("ApartmentBuilding", symaware::Environment::ObjectType::ApartmentBuilding)
      .value("ArrowBoard_Trailer", symaware::Environment::ObjectType::ArrowBoard_Trailer)
      .value("Ash10y", symaware::Environment::ObjectType::Ash10y)
      .value("Ash20y", symaware::Environment::ObjectType::Ash20y)
      .value("Audi_A3", symaware::Environment::ObjectType::Audi_A3)
      .value("Audi_A8_Sedan", symaware::Environment::ObjectType::Audi_A8_Sedan)
      .value("AustrianPine10y", symaware::Environment::ObjectType::AustrianPine10y)
      .value("AustrianPine20y", symaware::Environment::ObjectType::AustrianPine20y)
      .value("BE_Police_Volvo_XC60", symaware::Environment::ObjectType::BE_Police_Volvo_XC60)
      .value("BMW_X5_SUV", symaware::Environment::ObjectType::BMW_X5_SUV)
      .value("BMW_Z3_Convertible", symaware::Environment::ObjectType::BMW_Z3_Convertible)
      .value("BalloonCar", symaware::Environment::ObjectType::BalloonCar)
      .value("BarrierFence", symaware::Environment::ObjectType::BarrierFence)
      .value("Birch10y", symaware::Environment::ObjectType::Birch10y)
      .value("Birch20y", symaware::Environment::ObjectType::Birch20y)
      .value("BlueSpruce10y", symaware::Environment::ObjectType::BlueSpruce10y)
      .value("BlueSpruce20y", symaware::Environment::ObjectType::BlueSpruce20y)
      .value("BottsDots_White", symaware::Environment::ObjectType::BottsDots_White)
      .value("BottsDots_Yellow", symaware::Environment::ObjectType::BottsDots_Yellow)
      .value("Boy_100", symaware::Environment::ObjectType::Boy_100)
      .value("Boy_150", symaware::Environment::ObjectType::Boy_150)
      .value("Building_00A", symaware::Environment::ObjectType::Building_00A)
      .value("Building_01A", symaware::Environment::ObjectType::Building_01A)
      .value("Building_02A", symaware::Environment::ObjectType::Building_02A)
      .value("Building_03A", symaware::Environment::ObjectType::Building_03A)
      .value("Building_04A", symaware::Environment::ObjectType::Building_04A)
      .value("Building_05A", symaware::Environment::ObjectType::Building_05A)
      .value("Building_06A", symaware::Environment::ObjectType::Building_06A)
      .value("Building_07A", symaware::Environment::ObjectType::Building_07A)
      .value("Building_08A", symaware::Environment::ObjectType::Building_08A)
      .value("Busstop", symaware::Environment::ObjectType::Busstop)
      .value("CAT_725", symaware::Environment::ObjectType::CAT_725)
      .value("Cadillac_Escalade", symaware::Environment::ObjectType::Cadillac_Escalade)
      .value("CarDealer", symaware::Environment::ObjectType::CarDealer)
      .value("Car_Trailer_Small", symaware::Environment::ObjectType::Car_Trailer_Small)
      .value("CatsEyesR", symaware::Environment::ObjectType::CatsEyesR)
      .value("CatsEyesW", symaware::Environment::ObjectType::CatsEyesW)
      .value("CatsEyesWR", symaware::Environment::ObjectType::CatsEyesWR)
      .value("CatsEyesWY", symaware::Environment::ObjectType::CatsEyesWY)
      .value("CatsEyesY", symaware::Environment::ObjectType::CatsEyesY)
      .value("Child_Leaning", symaware::Environment::ObjectType::Child_Leaning)
      .value("Child_Overweight", symaware::Environment::ObjectType::Child_Overweight)
      .value("Child_Regular", symaware::Environment::ObjectType::Child_Regular)
      .value("Child_Sitting", symaware::Environment::ObjectType::Child_Sitting)
      .value("CinderBlock_A", symaware::Environment::ObjectType::CinderBlock_A)
      .value("CinderBlock_B", symaware::Environment::ObjectType::CinderBlock_B)
      .value("CinderBlock_C", symaware::Environment::ObjectType::CinderBlock_C)
      .value("Citroen_C3_Hatchback", symaware::Environment::ObjectType::Citroen_C3_Hatchback)
      .value("ConstructionSign_JP", symaware::Environment::ObjectType::ConstructionSign_JP)
      .value("Container_Trailer", symaware::Environment::ObjectType::Container_Trailer)
      .value("CornerReflector138mm", symaware::Environment::ObjectType::CornerReflector138mm)
      .value("CornerReflector176_8mm", symaware::Environment::ObjectType::CornerReflector176_8mm)
      .value("CornerReflector46_35mm", symaware::Environment::ObjectType::CornerReflector46_35mm)
      .value("Cotton_A", symaware::Environment::ObjectType::Cotton_A)
      .value("Cotton_B", symaware::Environment::ObjectType::Cotton_B)
      .value("Cotton_C", symaware::Environment::ObjectType::Cotton_C)
      .value("DAF_95_XF", symaware::Environment::ObjectType::DAF_95_XF)
      .value("DAF_Euro_6_XF", symaware::Environment::ObjectType::DAF_Euro_6_XF)
      .value("Deer", symaware::Environment::ObjectType::Deer)
      .value("Dogwood10y", symaware::Environment::ObjectType::Dogwood10y)
      .value("Dogwood20y", symaware::Environment::ObjectType::Dogwood20y)
      .value("Dumpster_2300L", symaware::Environment::ObjectType::Dumpster_2300L)
      .value("DutchChurch", symaware::Environment::ObjectType::DutchChurch)
      .value("Empty_Light_Node", symaware::Environment::ObjectType::Empty_Light_Node)
      .value("FAW_Jiefang_J6M", symaware::Environment::ObjectType::FAW_Jiefang_J6M)
      .value("FShape150cm", symaware::Environment::ObjectType::FShape150cm)
      .value("FShape250cm", symaware::Environment::ObjectType::FShape250cm)
      .value("FShape350cm", symaware::Environment::ObjectType::FShape350cm)
      .value("Female_Bending", symaware::Environment::ObjectType::Female_Bending)
      .value("Female_Leaning", symaware::Environment::ObjectType::Female_Leaning)
      .value("Female_Overweight", symaware::Environment::ObjectType::Female_Overweight)
      .value("Female_Regular", symaware::Environment::ObjectType::Female_Regular)
      .value("Female_wBuggy", symaware::Environment::ObjectType::Female_wBuggy)
      .value("Female_wLongCoat", symaware::Environment::ObjectType::Female_wLongCoat)
      .value("Female_wRaincoat", symaware::Environment::ObjectType::Female_wRaincoat)
      .value("Female_wShoppingCart", symaware::Environment::ObjectType::Female_wShoppingCart)
      .value("Fiat_Bravo_Hatchback", symaware::Environment::ObjectType::Fiat_Bravo_Hatchback)
      .value("FireBrigade", symaware::Environment::ObjectType::FireBrigade)
      .value("Ford_Fiesta_Hatchback", symaware::Environment::ObjectType::Ford_Fiesta_Hatchback)
      .value("Ford_Focus_Stationwagon", symaware::Environment::ObjectType::Ford_Focus_Stationwagon)
      .value("Full_Trailer", symaware::Environment::ObjectType::Full_Trailer)
      .value("Garage_Ground_Floor", symaware::Environment::ObjectType::Garage_Ground_Floor)
      .value("Garage_Mid_Floor", symaware::Environment::ObjectType::Garage_Mid_Floor)
      .value("Garage_Top_Floor", symaware::Environment::ObjectType::Garage_Top_Floor)
      .value("GasStation", symaware::Environment::ObjectType::GasStation)
      .value("Genesis_GV80", symaware::Environment::ObjectType::Genesis_GV80)
      .value("GuardrailReflector_RectR", symaware::Environment::ObjectType::GuardrailReflector_RectR)
      .value("GuardrailReflector_RectW", symaware::Environment::ObjectType::GuardrailReflector_RectW)
      .value("GuardrailReflector_RectWR", symaware::Environment::ObjectType::GuardrailReflector_RectWR)
      .value("GuardrailReflector_RoundR", symaware::Environment::ObjectType::GuardrailReflector_RoundR)
      .value("GuardrailReflector_RoundW", symaware::Environment::ObjectType::GuardrailReflector_RoundW)
      .value("GuardrailReflector_RoundWR", symaware::Environment::ObjectType::GuardrailReflector_RoundWR)
      .value("GuardrailReflector_RoundY", symaware::Environment::ObjectType::GuardrailReflector_RoundY)
      .value("GuidedSoftTarget", symaware::Environment::ObjectType::GuidedSoftTarget)
      .value("HOWO_T5G_Cement_Truck", symaware::Environment::ObjectType::HOWO_T5G_Cement_Truck)
      .value("Hino_Blue_Ribbon", symaware::Environment::ObjectType::Hino_Blue_Ribbon)
      .value("Honda_Pan_European_Motorcycle", symaware::Environment::ObjectType::Honda_Pan_European_Motorcycle)
      .value("Honda_Pan_European_Motorcycle_With_Driver",
             symaware::Environment::ObjectType::Honda_Pan_European_Motorcycle_With_Driver)
      .value("HouseModern", symaware::Environment::ObjectType::HouseModern)
      .value("HouseOld1", symaware::Environment::ObjectType::HouseOld1)
      .value("HouseOld2", symaware::Environment::ObjectType::HouseOld2)
      .value("HouseOld3", symaware::Environment::ObjectType::HouseOld3)
      .value("HouseOld4", symaware::Environment::ObjectType::HouseOld4)
      .value("HouseOld5", symaware::Environment::ObjectType::HouseOld5)
      .value("HouseOld6", symaware::Environment::ObjectType::HouseOld6)
      .value("Houses1930s", symaware::Environment::ObjectType::Houses1930s)
      .value("Hyundai_Ioniq5", symaware::Environment::ObjectType::Hyundai_Ioniq5)
      .value("Hyundai_i30_NLine", symaware::Environment::ObjectType::Hyundai_i30_NLine)
      .value("Isuzu_DMax", symaware::Environment::ObjectType::Isuzu_DMax)
      .value("Isuzu_Giga_Fire_Truck", symaware::Environment::ObjectType::Isuzu_Giga_Fire_Truck)
      .value("JAC_HFC_Series", symaware::Environment::ObjectType::JAC_HFC_Series)
      .value("JapaneseMaple10y", symaware::Environment::ObjectType::JapaneseMaple10y)
      .value("JapaneseMaple20y", symaware::Environment::ObjectType::JapaneseMaple20y)
      .value("Joby_Aviation_S4", symaware::Environment::ObjectType::Joby_Aviation_S4)
      .value("Kia_EV6", symaware::Environment::ObjectType::Kia_EV6)
      .value("Kia_EV6_wRoofRack", symaware::Environment::ObjectType::Kia_EV6_wRoofRack)
      .value("Kia_EV6_wRoofRack_Siemens", symaware::Environment::ObjectType::Kia_EV6_wRoofRack_Siemens)
      .value("Lexus_GS_450h_F_Sport_Sedan", symaware::Environment::ObjectType::Lexus_GS_450h_F_Sport_Sedan)
      .value("Lexus_LS_600h_F_Sport", symaware::Environment::ObjectType::Lexus_LS_600h_F_Sport)
      .value("LightPost", symaware::Environment::ObjectType::LightPost)
      .value("Lilac10y", symaware::Environment::ObjectType::Lilac10y)
      .value("Lilac20y", symaware::Environment::ObjectType::Lilac20y)
      .value("Magnolia10y", symaware::Environment::ObjectType::Magnolia10y)
      .value("Magnolia20y", symaware::Environment::ObjectType::Magnolia20y)
      .value("Male_200", symaware::Environment::ObjectType::Male_200)
      .value("Male_African", symaware::Environment::ObjectType::Male_African)
      .value("Male_Bending", symaware::Environment::ObjectType::Male_Bending)
      .value("Male_BendingOver", symaware::Environment::ObjectType::Male_BendingOver)
      .value("Male_CyclingCyclist", symaware::Environment::ObjectType::Male_CyclingCyclist)
      .value("Male_Female_HandInHand", symaware::Environment::ObjectType::Male_Female_HandInHand)
      .value("Male_LargeShoulderSuitcase", symaware::Environment::ObjectType::Male_LargeShoulderSuitcase)
      .value("Male_Leaning", symaware::Environment::ObjectType::Male_Leaning)
      .value("Male_LeaningBack", symaware::Environment::ObjectType::Male_LeaningBack)
      .value("Male_LyingDown", symaware::Environment::ObjectType::Male_LyingDown)
      .value("Male_Old_White_WithStick", symaware::Environment::ObjectType::Male_Old_White_WithStick)
      .value("Male_Old_White_WithWalker", symaware::Environment::ObjectType::Male_Old_White_WithWalker)
      .value("Male_Old_White_WithWalkerWithWheels",
             symaware::Environment::ObjectType::Male_Old_White_WithWalkerWithWheels)
      .value("Male_Overweight", symaware::Environment::ObjectType::Male_Overweight)
      .value("Male_Regular", symaware::Environment::ObjectType::Male_Regular)
      .value("Male_ShoppingBag", symaware::Environment::ObjectType::Male_ShoppingBag)
      .value("Male_Sitting", symaware::Environment::ObjectType::Male_Sitting)
      .value("Male_wBackpack", symaware::Environment::ObjectType::Male_wBackpack)
      .value("Male_wBicycle", symaware::Environment::ObjectType::Male_wBicycle)
      .value("Male_wLargeBackpack", symaware::Environment::ObjectType::Male_wLargeBackpack)
      .value("Male_wLongCoat", symaware::Environment::ObjectType::Male_wLongCoat)
      .value("Male_wRaincoat", symaware::Environment::ObjectType::Male_wRaincoat)
      .value("Male_wSuit", symaware::Environment::ObjectType::Male_wSuit)
      .value("Male_wSuitcase", symaware::Environment::ObjectType::Male_wSuitcase)
      .value("Man_250", symaware::Environment::ObjectType::Man_250)
      .value("Man_Asian", symaware::Environment::ObjectType::Man_Asian)
      .value("Mazda_RX8_Coupe", symaware::Environment::ObjectType::Mazda_RX8_Coupe)
      .value("MercedesBenz_Actros_1851_LS_4x2", symaware::Environment::ObjectType::MercedesBenz_Actros_1851_LS_4x2)
      .value("MercedesBenz_Actros_1860_LS_4x2", symaware::Environment::ObjectType::MercedesBenz_Actros_1860_LS_4x2)
      .value("MercedesBenz_Actros_2541_L_6x2", symaware::Environment::ObjectType::MercedesBenz_Actros_2541_L_6x2)
      .value("Mitsubishi_Outlander_PHEV", symaware::Environment::ObjectType::Mitsubishi_Outlander_PHEV)
      .value("Monument", symaware::Environment::ObjectType::Monument)
      .value("NCAP_Adult", symaware::Environment::ObjectType::NCAP_Adult)
      .value("NCAP_Child", symaware::Environment::ObjectType::NCAP_Child)
      .value("NCAP_Cyclist", symaware::Environment::ObjectType::NCAP_Cyclist)
      .value("NCAP_EBTA", symaware::Environment::ObjectType::NCAP_EBTA)
      .value("NCAP_GVT", symaware::Environment::ObjectType::NCAP_GVT)
      .value("NCAP_Motorcycle", symaware::Environment::ObjectType::NCAP_Motorcycle)
      .value("NCAP_Scooter", symaware::Environment::ObjectType::NCAP_Scooter)
      .value("NCAP_StreetLight", symaware::Environment::ObjectType::NCAP_StreetLight)
      .value("NL_Ambulance_Volvo_XC60", symaware::Environment::ObjectType::NL_Ambulance_Volvo_XC60)
      .value("Nissan_Ariya", symaware::Environment::ObjectType::Nissan_Ariya)
      .value("Nissan_Cabstar_Boxtruck", symaware::Environment::ObjectType::Nissan_Cabstar_Boxtruck)
      .value("Object", symaware::Environment::ObjectType::Object)
      .value("OfficeBrownFlat", symaware::Environment::ObjectType::OfficeBrownFlat)
      .value("OfficeBrownTall1", symaware::Environment::ObjectType::OfficeBrownTall1)
      .value("OfficeBrownTall2", symaware::Environment::ObjectType::OfficeBrownTall2)
      .value("OfficeGreenTall", symaware::Environment::ObjectType::OfficeGreenTall)
      .value("Overhang1Light_JP", symaware::Environment::ObjectType::Overhang1Light_JP)
      .value("Overhang1Light_KR", symaware::Environment::ObjectType::Overhang1Light_KR)
      .value("Overhang1Light_NL", symaware::Environment::ObjectType::Overhang1Light_NL)
      .value("Overhang1Light_US", symaware::Environment::ObjectType::Overhang1Light_US)
      .value("Overhang1Post_JP", symaware::Environment::ObjectType::Overhang1Post_JP)
      .value("Overhang1Post_KR", symaware::Environment::ObjectType::Overhang1Post_KR)
      .value("Overhang1Post_NL", symaware::Environment::ObjectType::Overhang1Post_NL)
      .value("Overhang1Post_US", symaware::Environment::ObjectType::Overhang1Post_US)
      .value("Overhang2Lights_JP", symaware::Environment::ObjectType::Overhang2Lights_JP)
      .value("Overhang2Lights_KR", symaware::Environment::ObjectType::Overhang2Lights_KR)
      .value("Overhang2Lights_NL", symaware::Environment::ObjectType::Overhang2Lights_NL)
      .value("Overhang2Lights_US", symaware::Environment::ObjectType::Overhang2Lights_US)
      .value("Overhang2Post_JP", symaware::Environment::ObjectType::Overhang2Post_JP)
      .value("Overhang2Post_KR", symaware::Environment::ObjectType::Overhang2Post_KR)
      .value("Overhang2Post_NL", symaware::Environment::ObjectType::Overhang2Post_NL)
      .value("Overhang2Post_US", symaware::Environment::ObjectType::Overhang2Post_US)
      .value("OverhangDH2Lights_US", symaware::Environment::ObjectType::OverhangDH2Lights_US)
      .value("OverhangDHPost_US", symaware::Environment::ObjectType::OverhangDHPost_US)
      .value("Pallet", symaware::Environment::ObjectType::Pallet)
      .value("PedestrianSignal_JP", symaware::Environment::ObjectType::PedestrianSignal_JP)
      .value("Peterbilt_579", symaware::Environment::ObjectType::Peterbilt_579)
      .value("Peterbilt_579_Trailer", symaware::Environment::ObjectType::Peterbilt_579_Trailer)
      .value("PlasticBarrier100cm", symaware::Environment::ObjectType::PlasticBarrier100cm)
      .value("PrismSignV_30_50_70", symaware::Environment::ObjectType::PrismSignV_30_50_70)
      .value("PrismSignV_5_10_15", symaware::Environment::ObjectType::PrismSignV_5_10_15)
      .value("PrismSignV_80_100_110", symaware::Environment::ObjectType::PrismSignV_80_100_110)
      .value("PrismSign_30_50_70", symaware::Environment::ObjectType::PrismSign_30_50_70)
      .value("PrismSign_5_10_15", symaware::Environment::ObjectType::PrismSign_5_10_15)
      .value("PrismSign_80_100_110", symaware::Environment::ObjectType::PrismSign_80_100_110)
      .value("Pylon_01", symaware::Environment::ObjectType::Pylon_01)
      .value("Pylon_02", symaware::Environment::ObjectType::Pylon_02)
      .value("ReflectorSign", symaware::Environment::ObjectType::ReflectorSign)
      .value("ReflectorSignSimple", symaware::Environment::ObjectType::ReflectorSignSimple)
      .value("Rivian_R1T", symaware::Environment::ObjectType::Rivian_R1T)
      .value("Rivian_R1T_wCover", symaware::Environment::ObjectType::Rivian_R1T_wCover)
      .value("RoadClosed_wLights", symaware::Environment::ObjectType::RoadClosed_wLights)
      .value("RoadsideLight_NL", symaware::Environment::ObjectType::RoadsideLight_NL)
      .value("RoadsideMarker", symaware::Environment::ObjectType::RoadsideMarker)
      .value("RoadsidePost", symaware::Environment::ObjectType::RoadsidePost)
      .value("RoadsidePost_NL", symaware::Environment::ObjectType::RoadsidePost_NL)
      .value("Roewe_550_S_Sedan", symaware::Environment::ObjectType::Roewe_550_S_Sedan)
      .value("Row_Crop_Tractor", symaware::Environment::ObjectType::Row_Crop_Tractor)
      .value("School", symaware::Environment::ObjectType::School)
      .value("Scooter", symaware::Environment::ObjectType::Scooter)
      .value("Scooter_wBox", symaware::Environment::ObjectType::Scooter_wBox)
      .value("Serviceberry10y", symaware::Environment::ObjectType::Serviceberry10y)
      .value("Serviceberry15y", symaware::Environment::ObjectType::Serviceberry15y)
      .value("Serviceberry5y", symaware::Environment::ObjectType::Serviceberry5y)
      .value("ShoppingCart", symaware::Environment::ObjectType::ShoppingCart)
      .value("Siemens_eRod", symaware::Environment::ObjectType::Siemens_eRod)
      .value("SignalCasing20cm_NL", symaware::Environment::ObjectType::SignalCasing20cm_NL)
      .value("SignalCasing30cmDH_US", symaware::Environment::ObjectType::SignalCasing30cmDH_US)
      .value("SignalCasing30cm_JP", symaware::Environment::ObjectType::SignalCasing30cm_JP)
      .value("SignalCasing30cm_NL", symaware::Environment::ObjectType::SignalCasing30cm_NL)
      .value("SignalCasing30cm_US", symaware::Environment::ObjectType::SignalCasing30cm_US)
      .value("SignalCasing3_30cm_KR", symaware::Environment::ObjectType::SignalCasing3_30cm_KR)
      .value("SignalCasing4_30cm_KR", symaware::Environment::ObjectType::SignalCasing4_30cm_KR)
      .value("Skywell", symaware::Environment::ObjectType::Skywell)
      .value("SpeedBump250cm", symaware::Environment::ObjectType::SpeedBump250cm)
      .value("SpeedBump350cm", symaware::Environment::ObjectType::SpeedBump350cm)
      .value("Sports_Bike", symaware::Environment::ObjectType::Sports_Bike)
      .value("Sports_Bike_wDriver", symaware::Environment::ObjectType::Sports_Bike_wDriver)
      .value("SpringPost46cm", symaware::Environment::ObjectType::SpringPost46cm)
      .value("SpringPost75cm", symaware::Environment::ObjectType::SpringPost75cm)
      .value("SpringPost95cm", symaware::Environment::ObjectType::SpringPost95cm)
      .value("Suzuki_Hustler_Hybrid", symaware::Environment::ObjectType::Suzuki_Hustler_Hybrid)
      .value("TerracedHouses", symaware::Environment::ObjectType::TerracedHouses)
      .value("Tesla_Model_3", symaware::Environment::ObjectType::Tesla_Model_3)
      .value("Tire_Horizontal", symaware::Environment::ObjectType::Tire_Horizontal)
      .value("Tire_Vertical", symaware::Environment::ObjectType::Tire_Vertical)
      .value("Toddler_050", symaware::Environment::ObjectType::Toddler_050)
      .value("Toyota_Previa_MPV", symaware::Environment::ObjectType::Toyota_Previa_MPV)
      .value("Toyota_Prius_Sedan", symaware::Environment::ObjectType::Toyota_Prius_Sedan)
      .value("Toyota_Yaris_Hatchback", symaware::Environment::ObjectType::Toyota_Yaris_Hatchback)
      .value("TrashBin_240L", symaware::Environment::ObjectType::TrashBin_240L)
      .value("TrashCan_Rnd_130L", symaware::Environment::ObjectType::TrashCan_Rnd_130L)
      .value("TrashCan_Sqr_160L", symaware::Environment::ObjectType::TrashCan_Sqr_160L)
      .value("TriangleParkingSpaceLock", symaware::Environment::ObjectType::TriangleParkingSpaceLock)
      .value("TurkishHazel10y", symaware::Environment::ObjectType::TurkishHazel10y)
      .value("TurkishHazel20y", symaware::Environment::ObjectType::TurkishHazel20y)
      .value("US_Police_Volvo_XC60", symaware::Environment::ObjectType::US_Police_Volvo_XC60)
      .value("VehicleSignal30cm_FL_JP", symaware::Environment::ObjectType::VehicleSignal30cm_FL_JP)
      .value("VehicleSignal30cm_FR_JP", symaware::Environment::ObjectType::VehicleSignal30cm_FR_JP)
      .value("VehicleSignal30cm_F_JP", symaware::Environment::ObjectType::VehicleSignal30cm_F_JP)
      .value("VehicleSignal30cm_L_JP", symaware::Environment::ObjectType::VehicleSignal30cm_L_JP)
      .value("VehicleSignal30cm_R_JP", symaware::Environment::ObjectType::VehicleSignal30cm_R_JP)
      .value("VehicleSignalGreen30cm_JP", symaware::Environment::ObjectType::VehicleSignalGreen30cm_JP)
      .value("VehicleSignalOrange30cm_JP", symaware::Environment::ObjectType::VehicleSignalOrange30cm_JP)
      .value("VehicleSignalRed30cm_JP", symaware::Environment::ObjectType::VehicleSignalRed30cm_JP)
      .value("Volvo_FH16", symaware::Environment::ObjectType::Volvo_FH16)
      .value("Volvo_XC60", symaware::Environment::ObjectType::Volvo_XC60)
      .value("Warehouse", symaware::Environment::ObjectType::Warehouse)
      .value("Wheat_A", symaware::Environment::ObjectType::Wheat_A)
      .value("Wheat_B", symaware::Environment::ObjectType::Wheat_B)
      .value("Wheat_C", symaware::Environment::ObjectType::Wheat_C)
      .value("WheelieBin_1100L", symaware::Environment::ObjectType::WheelieBin_1100L)
      .value("Windmill", symaware::Environment::ObjectType::Windmill)
      .value("Wuling_Hongguang", symaware::Environment::ObjectType::Wuling_Hongguang)
      .value("Church", symaware::Environment::ObjectType::Church)
      .value("Factory", symaware::Environment::ObjectType::Factory)
      .value("ConcreteGuardrail", symaware::Environment::ObjectType::ConcreteGuardrail)
      .value("Guardrail", symaware::Environment::ObjectType::Guardrail)
      .value("Fence", symaware::Environment::ObjectType::Fence)
      .value("LinePlacedRoadImperfection", symaware::Environment::ObjectType::LinePlacedRoadImperfection)
      .value("SoundAbsorbingWall", symaware::Environment::ObjectType::SoundAbsorbingWall)
      .value("Wall", symaware::Environment::ObjectType::Wall)
      .value("House", symaware::Environment::ObjectType::House)
      .value("Office", symaware::Environment::ObjectType::Office)
      .value("Box", symaware::Environment::ObjectType::Box)
      .value("Capsule", symaware::Environment::ObjectType::Capsule)
      .value("Cone", symaware::Environment::ObjectType::Cone)
      .value("Cylinder", symaware::Environment::ObjectType::Cylinder)
      .value("Sphere", symaware::Environment::ObjectType::Sphere)
      .value("Tripod", symaware::Environment::ObjectType::Tripod)
      .value("TrafficSignPole", symaware::Environment::ObjectType::TrafficSignPole);

  environment.def(py::init<>())
      .def(py::init<const std::string &>())
      .def("set_weather", &symaware::Environment::setWeather, "Set the weather of the environment",
           py::arg("weather_type") = symaware::Environment::WeatherType::SUNNY, py::arg("fog_visibility") = -1)
      .def("set_sky", &symaware::Environment::setSky, "Set the sky of the environment",
           py::arg("sky_type") = symaware::Environment::SkyType::DAY,
           py::arg("light_pollution") = prescan::api::types::SkyLightPollution::SkyLightPollutionNone)
      .def("set_scheduler_frequencies", &symaware::Environment::setSchedulerFrequencies,
           "Set the scheduler frequencies of the environment", py::arg("simulation_frequency"),
           py::arg("integration_frequency"))
      .def("set_scheduler_speed", &symaware::Environment::setSchedulerSpeed,
           "Set the scheduler speed of the environment", py::arg("simulation_speed"), py::arg("ignore_frame_overrun"))
      .def("add_entity", &symaware::Environment::addEntity, "Add an entity to the environment", py::arg("entity"))
      .def("add_road", &symaware::Environment::addRoad, "Add a road to the environment",
           py::arg("position") = symaware::Position{true})
      .def("create_free_viewer", &symaware::Environment::createFreeViewer, "Create a free viewer in the environment")
      .def("remove_all_viewers", &symaware::Environment::removeAllViewers, "Remove all viewers from the environment")

      .def_property_readonly("entities", &symaware::Environment::entities, "Get the entities in the environment")
      .def_property_readonly("experiment", &symaware::Environment::experiment, "Get the experiment of the environment");
}
